### ISSUE TITLE
why different pacakge for v7 and v6 but not for v8?

### ISSUE THREAD

**Issue by lfarkas** [fg2it/grafana-on-raspberry#14]
Hi,
unfortunately it's takes me too long to figure out that mya brand new pi zerow has the old v6 cpu son i can't use the same package as on my pi3. is there any good reason why not use the same package on all pi as eg influx do his pacakge whic hcan be run on all raspberry pi. does it really has any advantage to build with different instruction set?

**Comment by fg2it** [comment]
In theory, performance-wise, you should get some benefit. In practice, I didn't try to benchmark.
For Grafana itself, it might not be that much, but I hope that for phantomjs (which is used to render png) it is a bit more.
If you don't want to bother, the pi1 package should work on all pi (it should be stated somewhere in the wiki).
