### ISSUE TITLE
update to 4.3.2

### ISSUE THREAD

**Issue by lfarkas** [fg2it/grafana-on-raspberry#15]
hi,
since upstream release 4.3.2 it'd be nice to update pi packages too.
regards.

**Comment by fg2it** [comment]
I know, sorry for that. I will try to find some time in the next few days.

**Comment by fg2it** [comment]
wish you'll find joy and happiness in the last release 😉

**Comment by TotallyInformation** [comment]
Sorry to be a pain but is there any chance of this being added to the debian repo? It would make life a lot easier ;)

**Comment by fg2it** [comment]
Hum, this is supposed to be automated. Travis ci takes care of deployment on github release page and bintray deb repo. And as far as I can see, the packages have been deployed.

**Comment by TotallyInformation** [comment]
Oh, maybe my bad, sorry. I checked the repo before you updated but just ran an apt-get update/upgrade afterwards, I guess I need to force it to move to the new version, I'll check when I get back to the Pi.

**Comment by TotallyInformation** [comment]
Odd, it didn't find the upgrade until I forced it by re-adding the repo. Got it now though. As always many thanks for your work on this, it is a real life-saver.
