### ISSUE TITLE
newer version again 4.4.1

### ISSUE THREAD

**Issue by lfarkas** [fg2it/grafana-on-raspberry#17]

**Comment by lfarkas** [comment]
any chance? it'd be nice to write a short howto create these binaries. so that everyone can build it.

**Comment by Bronkoknorb** [comment]
New version would be appreciated!
(But the instructions are here: https://github.com/fg2it/grafana-on-raspberry/blob/master/ci/README.md - It can be done by everybody.)

**Comment by jhlweb** [comment]
Hi @fg2it any idea if you're going to make a 4.4 version build for grafana any time soon? It would be very nice to have an update. Or are U waiting for grafana 5?

**Comment by fg2it** [comment]
done

**Comment by sarphram** [comment]
Thank you for updating the packages @fg2it

**Comment by jhlweb** [comment]
Thanks for the update.
