### ISSUE TITLE
Grafana Config Files cannot be mounted

### ISSUE THREAD

**Issue by dampfnudel** [fg2it/grafana-on-raspberry#18]
I have the feeling there is no persistent storage of the config files possible.

**Comment by fg2it** [comment]
This is not something specific to my build. I think the [official docker image](https://github.com/grafana/grafana-docker) may have some hints on how to do that. The docker cli allows to mount host volume or to create persistent volume and mount them, see [here](https://github.com/fg2it/grafana-on-raspberry/tree/master/docker/v4.x#grafana-container-with-persistent-storage-recommended) or the docker doc.
