### ISSUE TITLE
No key for Rpi1 install

### ISSUE THREAD

**Issue by bphermansson** [fg2it/grafana-on-raspberry#19]
I follow the Wiki instructions to install on a RPI 1. I get the following error:

`curl https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  717k  100  717k    0     0   177k      0  0:00:04  0:00:04 --:--:--  177k
gpg: no valid OpenPGP data found.
`

And of course apt says:

`
sudo apt-get update
...
W: GPG error: https://dl.bintray.com jessie Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379...
`

**Comment by fg2it** [comment]
do you still have this problem ? I just tried and bintray pubkey is still available at this url. Probably a temporary failure, either your isp, bintray or elsewhere.
