### ISSUE TITLE
Not clear what to do

### ISSUE THREAD

**Issue by delchrys** [fg2it/grafana-on-raspberry#2]
It is still not clear what I have to do to install grafana on my rpi2.  Do I download the. Deb FILe and build it or do I have to do the whole procedure in the Readme file?

**Comment by fg2it** [comment]
@delchrys 
Sorry for being unclear. You have two ways : 
- download the .deb and install it, for example if your rpi2 is running raspbian jessie, the following should do the job : 

``` bash
#jessie
cd /tmp
curl -LO https://raw.githubusercontent.com/fg2it/grafana-on-raspberry/master/jessie/v2.6.0/grafana_2.6.0_armhf.deb
sudo dpkg -i grafana_2.6.0_armhf.deb
```
- or you can follow the instructions in the readme.
  The differences are simple : the first way is easy but you need to trust my **unofficial** package; the second takes more work but you don't have to trust my package.

I didn't provide a .deb for grafana v2.6.0 on wheezy so for now, you cannot have the easy way if you are running wheezy and want v2.6.0. But, you can still have the easy way on wheezy if you accept older version.

In case you wonder if you are running jessie or wheezy, you can check that using

``` bash
cat /etc/debian_version
```

If the answer is 8.0, you're on jessie. If it is 7, you're on wheezy.

I plan to provide the v2.6.0 .deb for wheezy soon.

Hope it helps.

**Comment by delchrys** [comment]
And then that's it.? 
Grafana installed? 
Wow hope it works, thanks

**Comment by fg2it** [comment]
Yes, then it is install. Then you can see the official documentation for how to configure and start it.
