### ISSUE TITLE
Repository for Raspbian (Debian) Stretch

### ISSUE THREAD

**Issue by ghost** [fg2it/grafana-on-raspberry#20]
Thank you for your awesome work providing Grafana packages for the Raspberry Pi for easy installation.

Since Debian Stretch was released a few months ago and Raspbian also released their version based on Debian Stretch it would be  awesome if the repository would be updated for Stretch.

**Comment by fg2it** [comment]
Right. Will do for the next package. Meanwhile, you can simply use the jessie repo.
