### ISSUE TITLE
Request Grafana 4.5.1 for ARMHF (Raspberry PI)

### ISSUE THREAD

**Issue by mtrohman** [fg2it/grafana-on-raspberry#22]
Hi, could you help me and others to build and share the new grafana 4.5.1 release for armhf. Thx

**Comment by hablaras** [comment]
Yes, please, waiting for 4.5 also!

**Comment by hablaras** [comment]
Thanks for the new version! Appreciate it!

**Comment by mtrohman** [comment]
thanks a lot
