### ISSUE TITLE
Missing Docker tag "latest" causes error

### ISSUE THREAD

**Issue by escalate** [fg2it/grafana-on-raspberry#25]
```
# docker pull fg2it/grafana-armhf
Using default tag: latest
Error response from daemon: manifest for fg2it/grafana-armhf:latest not found
```
The missing Docker tag "latest" causes the above errror message on my Raspbian system.
The official Grafana Docker image provides a "latest" tag and it is the default for Docker if you don't provide a specific tag name. 
Could you please provide the "latest" tag like the official Grafana Docker image does?

**Comment by fg2it** [comment]
Hi @escalate , thank you for the advice. Unfortunately, I see this as a feature and won't change that. I find the `latest` tag confusing and you end up with something that is not always what you want. Should it be the last image pushed ? The highest version number ? Should it include beta version ? Would it be nice to have an unwanted major upgrade ?
I would like a the highest version but, by default, no major update if already have an image (and I don't know what I would like if I had several images). `Latest` doesn't provide that and I don't want to do that by hand.
I find cleaner to let the user ask for a specific version. Sorry for the inconvenience.
