### ISSUE TITLE
Unable to retrieve metrics on Raspberry PI 1

### ISSUE THREAD

**Issue by mar1ged** [fg2it/grafana-on-raspberry#27]
I installed your build on my Raspberry but unfortunately it is not able to retrieve metrics from Prometheus. 

I`ve put a question on SO which provides some more background information about my installation. If you don't mind you could have a look there. If information is missing just give me a hint.

https://stackoverflow.com/questions/48082129/grafana-not-retrieving-metrics-query-inspector-is-idling

**Comment by fg2it** [comment]
Did you solve that ? Did you try with the docker container ?

**Comment by mar1ged** [comment]
No and no ;-)

I don't plan to install Docker on the Raspi1. I will close this issue and switch to my Raspi3 and give the Raspi1 to my son ...
