### ISSUE TITLE
Request for "latest" tag

### ISSUE THREAD

**Issue by x99percent** [fg2it/grafana-on-raspberry#29]
If you could tag the newest non-beta docker image with "latest", I'd really appreciate it! It would make auto-updates much easier with tools like watchtower.

**Comment by fg2it** [comment]
sorry, this is a feature, see #25

**Comment by x99percent** [comment]
"Latest" should represent the most recent non-beta release. Not using the docker-standard "latest" tag causes issues. This is detriment, not a feature.

**Comment by fg2it** [comment]
So detriment it is. If it is too cumbersome, use another images. Again, sorry but I don't intend to change that.

**Comment by x99percent** [comment]
I think you're missing the point that properly including the standard use of the "latest" tag does not prevent people from calling out specific image versions in the least.  You're blocking basic and standard functionality to protect a specific use-case that doesn't need protecting. Docker images don't auto-update on their own, but some people desire the ability to do **exactly** that with the use of other programs (e.g., watchtower).

Would you be so bold as to tell the folks maintaining Docker that they have it all wrong? I should hope not.
