### ISSUE TITLE
Request for armel packages

### ISSUE THREAD

**Issue by a0s** [fg2it/grafana-on-raspberry#33]
Hi, i have Odroid XU4
```
Linux manager 4.14.29-125 #1 SMP PREEMPT Thu Mar 22 21:40:52 UTC 2018 armv7l armv7l armv7l GNU/Linux
```
Could you build an armel version of the package pls?

**Comment by fg2it** [comment]
I think you need the armhf one. Check with `dpkg --print-architecture`.

**Comment by a0s** [comment]
Ok, on baremetal linux i have:
```
> uname -p -m -i
armv7l armv7l armv7l
> dpkg --print-architecture
armhf
> dpkg -i grafana_5.0.4_armhf.deb
OK
```

But inside docker `docker run --rm -it debian bash` i got strange behaviour:
```
> uname -p -m -i
armv7l unknown unknown
> dpkg --print-architecture
armel
> dpkg -i grafana_5.0.4_armhf.deb
dpkg: error processing archive grafana_5.0.4_armhf.deb (--install):
 package architecture (armhf) does not match system (armel)
Errors were encountered while processing:
 grafana_5.0.4_armhf.deb
```
I think it something about how docker works.
Yes, it is docker bug  https://github.com/moby/moby/issues/34875 :(

**Comment by a0s** [comment]
Ok, i found solution - using ubuntu instead of debian
```
root@manager:~# dpkg --print-architecture
armhf
root@manager:~# docker run --rm -it ubuntu dpkg --print-architecture
armhf
root@manager:~# docker run --rm -it debian dpkg --print-architecture
armel
```

**Comment by fg2it** [comment]
if you insiste for debian, try arm32v7/debian docker image. This is the one I use for [fg2it/grafana-armhf](https://hub.docker.com/r/fg2it/grafana-armhf/)
