### ISSUE TITLE
Another installation method

### ISSUE THREAD

**Issue by paulfantom** [fg2it/grafana-on-raspberry#35]
I wanted to let you know that we (@cloudalchemy) wrote an [ansible role to install grafana](https://github.com/cloudalchemy/ansible-grafana) on most platforms with various CPU architectures, not only x86_64. And somehow this role is currently one of recommended method of provisioning grafana according to [official docs](http://docs.grafana.org/administration/provisioning/#configuration-management-tools). It wouldn't be possible without you awesome work, so thanks a lot!

Just wanted to ask if you would add any info about this installation method somewhere in your docs?

**Comment by fg2it** [comment]
On of my main concern is to avoid having to much to maintain, so I try to keep the doc minimal and just refer globally to the grafana documentation. So, if it is already documented there, what would be the reason to duplicate that ?
Moreover I am not sure ansible is used a lot by users of this repo.

**Comment by paulfantom** [comment]
Sounds ok. Closing.
