### ISSUE TITLE
What is "PLUG IP" in rig-monitor.conf

### ISSUE THREAD

**Issue by choosetwo** [fg2it/grafana-on-raspberry#36]
Hello, 

I have discovered this projet Yesterday and it sedicung me like nothing ! ^^
I just block on one thing for the moment, 

In conf/rig-monitor.conf
RIG_LIST

I am not sure to understand what is the PLUG IP

Someone could tell me more about it ?
I know my rigs IP(s), is it the same IP ?

Thanks by advance 😃 

Wrong place, mb :)

**Comment by fg2it** [comment]
are you sure it is the right repo for this issue ? Because I don't know what your speaking about.
