### ISSUE TITLE
[Proposal] Docker ARM for Official 

### ISSUE THREAD

**Issue by RaymondMouthaan** [fg2it/grafana-on-raspberry#38]
Hi @fg2it,

I like to do the following proposal regarding grafana and docker:

- Use your knowledge to build deb for arm (PI1, PI2 and PI3) and arm64.
- Use my knowledge to build docker images for these packages (aka grafana:linux-arm and grafana:linux-arm64) + grafana:linux-amd64 with support for manifest list, so that one doesn't need to explicit set the tag/architecture.
- Merge all above into the official grafana docker project, so that there is only one place where all of this is maintained. 

What do you think about it? :-)

**Comment by fg2it** [comment]
As said in grafana/grafana-docker#117, this is planned by grafana team, both arm support and docker manifest.
The docker part is probably the easy part and is obviously blocked by offical arm support.
More work is needed for official builds on arm. Grafana staff is working on integrating all supported platforms + arm in the same build flows in their CI (you can track the status in grafana/grafana#9633).
So, maybe you can make a PR for the docker manifest part but I think it is a bit early. And for the offical arm support, It seams grafana team is on it.
