### ISSUE TITLE
Can this be installed in RPi Zero W?

### ISSUE THREAD

**Issue by jnherm** [fg2it/grafana-on-raspberry#39]
I have RPi Zero W V1.1 (openhabian) but I can't run grafana after installation.

● grafana-server.service - Grafana instance
   Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Sun 2018-05-06 23:18:18 +08; 2s ago
     Docs: http://docs.grafana.org
  Process: 3911 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.plugins=${PLUGINS_DIR} cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR} (code=killed, signal=ILL)
 Main PID: 3911 (code=killed, signal=ILL)

May 06 23:18:18 RadarCNSSO systemd[1]: grafana-server.service: Failed with result 'signal'.
May 06 23:18:18 RadarCNSSO systemd[1]: grafana-server.service: Service hold-off time over, scheduling restart.
May 06 23:18:18 RadarCNSSO systemd[1]: Stopped Grafana instance.
May 06 23:18:18 RadarCNSSO systemd[1]: grafana-server.service: Start request repeated too quickly.
May 06 23:18:18 RadarCNSSO systemd[1]: Failed to start Grafana instance.
May 06 23:18:18 RadarCNSSO systemd[1]: grafana-server.service: Unit entered failed state.
May 06 23:18:18 RadarCNSSO systemd[1]: grafana-server.service: Failed with result 'signal'.

**Comment by fg2it** [comment]
As far as I know, pi zero W uses the same processor as pi 1, so the version for pi 1 should be fine. Which version did you try ?

**Comment by fg2it** [comment]
no news being good news, let says this is solved
