### ISSUE TITLE
grafana/grafana docker is not armhf compatible yet

### ISSUE THREAD

**Issue by Proxx** [fg2it/grafana-on-raspberry#41]
i really love your armhf build. and since grafana support official bins on armhf its a big thumbs up for them
still the docker instance is only amd64 not arm

**Comment by fg2it** [comment]
@Proxx sorry but I stopped maintaining this repo. I invite you to support the [issue](https://github.com/grafana/grafana-docker/pull/177) that address your need in the official repo
