### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by mhaas** [fg2it/grafana-on-raspberry#5]
Not really an issue - but your docker packages helped me tremendously! Thanks :) If you are interested, I have some Dockerfiles for influxdb on ARM laying around.

**Comment by mhaas** [comment]
By the way, your Dockerfile also builds fine from armhf/debian:

```
diff --git a/docker/v3.x/Dockerfile b/docker/v3.x/Dockerfile
index 509a28b..20173c1 100644
--- a/docker/v3.x/Dockerfile
+++ b/docker/v3.x/Dockerfile
@@ -1,4 +1,5 @@
-FROM resin/armv7hf-debian:jessie
+#FROM resin/armv7hf-debian:jessie
+FROM armhf/debian:jessie

 ARG GRAFANA_VERSION
 ARG PKG_NAME
```

That's perhaps slightly cleaner - armhf/debian should be the semi-official Docker images. But I didn't check what the resin imasge actually contains :)

**Comment by fg2it** [comment]
@mhaas you are welcomed. Thank you for your proposal for influxdb, I also have that :-)
I don't remember why I took the resine images. I think I also checked the armhf/debian at that time but could not say why I stayed with resine.
