### ISSUE TITLE
Please provide Grafana 3.1.1

### ISSUE THREAD

**Issue by nbartels** [fg2it/grafana-on-raspberry#6]
Grafana 3.1.1 exists since August 1, 2016. Can you please provide Debian packages for this release, too.

Thanks a lot.

**Comment by vimagick** [comment]
👍  I'm waiting for it.

**Comment by fg2it** [comment]
@nbartels @vimagick I was on vacation but it is on my todo list for this week

**Comment by sarphram** [comment]
@fg2it thank you for providing this

**Comment by fg2it** [comment]
@nbartels @vimagick @sarphram done
