### ISSUE TITLE
Make packages also available for Ubuntu Trusty/Xenial?

### ISSUE THREAD

**Issue by Apollon77** [fg2it/grafana-on-raspberry#7]
Hey,

after searching for a current Grafana on ARMHF platform in deb package format I found your page.
I use Ubuntu Xenial/Trusty at the moment instead of Debian.

Do you see a chance to also make the packages available for that? Or can I directly use e.g. the Jessie package?
I just found out that Xenial seems tobe based on Debian Stretch, so what about packages for Stretch ? :-))  ...

Ingo Fischer

**Comment by fg2it** [comment]
try this [v3.1.1 release](https://github.com/fg2it/grafana-on-raspberry/releases/tag/v3.1.1-wheezy-jessie). I think it could work. I am pretty sure package I flagged for wheezy or jessie will at least have a problem with phantomjs related features (see [here](https://github.com/fg2it/grafana-on-raspberry/blob/master/README.md) and the other `README.md` files in `wheezy/` and `jessie/` for details). I change the phantomjs binary in the linked release which should help having a more portable package.

Please, tell me if it works for you.

**Comment by Apollon77** [comment]
Will try the next days, thank you!

**Comment by fg2it** [comment]
Made a quick test with docker for ubuntu xenial and trusty : it is working. Just take care to install dependencies `libfontconfig` and `libpng12-0`.
On debian stretch, it is also working but install of `libpng12-0` is not as easy since debian moved to libpng16. So you would have to import it from jessie. Nevertheless, this doesn't seems to create conflict.
And, by the way, you can also install docker.

**Comment by Apollon77** [comment]
I also thought about the docker version ... don't know if this ould create overhead on my CubieTruck :-) directly installed feels also ok when compatibe ... will try late today finally

**Comment by fg2it** [comment]
Without further update, I close this. Any feedback is welcomed.

**Comment by Apollon77** [comment]
Sorry for my "muting" but had installed it on a wheezy system ;-)

But now I have the real need to install on Ubuntu xenial ... so which v4 I should try The Jessie one?

**Comment by fg2it** [comment]
Starting with v3.1.1, there are no specific build for a distro. So, you only have to select the grafana version and the target raspberry pi version.
I made some tests and last release works fine on ubuntu/xenial and yakkety. See the new [faq](https://github.com/fg2it/grafana-on-raspberry/wiki/FAQ#i-am-using-ubuntu-can-i-use-your-packages-) if you need details.

**Comment by Apollon77** [comment]
Thank you, I tried the Docker version and have to say: works great (beside the plugin installing did not worked, but I could install them using "docker exec" ... :-) So I will use that in the next time I think :-)

**Comment by fg2it** [comment]
@Apollon77  Could you provides details on what had failed ? Was it the pluging install from the docker cli ? What was the plugin ?

**Comment by Apollon77** [comment]
Details see #11 (do not want to mix thing)
