### ISSUE TITLE
Error while installing for raspberry Pi 1 (B)

### ISSUE THREAD

**Issue by Atrejoe** [fg2it/grafana-on-raspberry#8]
As instructed on https://github.com/fg2it/grafana-on-raspberry/wiki, I added 

    echo "https://dl.bintray.com/fg2it/deb-rpi-1b jessie main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

However when running `apt-get update`, I get:

    E: Type 'https://dl.bintray.com/fg2it/deb-rpi-1b' is not known on line 1 in source list /etc/apt/sources.list.d/grafana.list
    E: The list of sources could not be read.

Upon closer inspected it _seemed_ the correct command should be:

    echo "deb https://dl.bintray.com/fg2it/deb-rpi-1b jessie main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
(note the **deb** )

Now `apt-get update` does get somewhat further, it returns: 

    W: Failed to fetch https://dl.bintray.com/fg2it/deb-rpi-1b/dists/jessie/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

    E: Some index files failed to download. They have been ignored, or old ones used instead.

Is there anything I should do?

Thanks for your effort of getting this to work on Raspberry Pi.

**Comment by Atrejoe** [comment]
My bad, I forgot to add the public key in time.

    curl https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -

However, when I now try to install grafana, I get:

```
$ sudo apt-get install grafana
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package grafana is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'grafana' has no installation candidate
```

**Comment by Atrejoe** [comment]
The contents of `release` (from https://dl.bintray.com/fg2it/deb-rpi-1b/dists/jessie/:Release ) seems to mention `test` packages only, could that be the issue?

```
Origin: Bintray
Label: Bintray
Suite: jessie
Codename: jessie
Date: Thu, 17 Nov 2016 22:42:05 UTC
Component: testing
Architectures: amd64 armhf i386
MD5Sum:
 d41d8cd98f00b204e9800998ecf8427e                0 testing/binary-amd64/Packages
 4059d198768f9f8dc9372dc1c54bc3c3               14 testing/binary-amd64/Packages.bz2
 3970e82605c7d109bb348fc94e9eecc0               20 testing/binary-amd64/Packages.gz
 8d44e90ad33fa3bfa13a5aba6f956662              471 testing/binary-armhf/Packages
 cceff50925bbd2c14d1d9e62b916c035              366 testing/binary-armhf/Packages.bz2
 c0b8712ddcebff77678841c0ed46d1e2              339 testing/binary-armhf/Packages.gz
 d41d8cd98f00b204e9800998ecf8427e                0 testing/binary-i386/Packages
 4059d198768f9f8dc9372dc1c54bc3c3               14 testing/binary-i386/Packages.bz2
 3970e82605c7d109bb348fc94e9eecc0               20 testing/binary-i386/Packages.gz
SHA1:
 da39a3ee5e6b4b0d3255bfef95601890afd80709                0 testing/binary-amd64/Packages
 64a543afbb5f4bf728636bdcbbe7a2ed0804adc2               14 testing/binary-amd64/Packages.bz2
 e03849ea786b9f7b28a35c17949e85a93eb1cff1               20 testing/binary-amd64/Packages.gz
 5fe69c3b2e250458c2c7e3eb55e6a383cadd320c              471 testing/binary-armhf/Packages
 62ebac31c4a1562c54bafd1864ed705536f7dee0              366 testing/binary-armhf/Packages.bz2
 64a5a2866d061fc7e6f1a3ca23dbc3c757408a79              339 testing/binary-armhf/Packages.gz
 da39a3ee5e6b4b0d3255bfef95601890afd80709                0 testing/binary-i386/Packages
 64a543afbb5f4bf728636bdcbbe7a2ed0804adc2               14 testing/binary-i386/Packages.bz2
 e03849ea786b9f7b28a35c17949e85a93eb1cff1               20 testing/binary-i386/Packages.gz
SHA256:
 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                0 testing/binary-amd64/Packages
 d3dda84eb03b9738d118eb2be78e246106900493c0ae07819ad60815134a8058               14 testing/binary-amd64/Packages.bz2
 f5d031af01f137ae07fa71720fab94d16cc8a2a59868766002918b7c240f3967               20 testing/binary-amd64/Packages.gz
 8c1a45ff70e725d1d9860af266f19683939ac914c067f1f2832c951d79162416              471 testing/binary-armhf/Packages
 031ae074e5a628753c7d57a09ec0fdc858983ef0d3ad8a9e281e9f5a9a08b4ac              366 testing/binary-armhf/Packages.bz2
 7b3a46dfe305beba25cd274baf3eb2548ac65bdf52496a64ba96f667a7f4ad15              339 testing/binary-armhf/Packages.gz
 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                0 testing/binary-i386/Packages
 d3dda84eb03b9738d118eb2be78e246106900493c0ae07819ad60815134a8058               14 testing/binary-i386/Packages.bz2
 f5d031af01f137ae07fa71720fab94d16cc8a2a59868766002918b7c240f3967               20 testing/binary-i386/Packages.gz
```

**Comment by Atrejoe** [comment]
Wow I overlooked the remark:

> change main for testing if you want to install beta release (currently, only testing is available for pi 1; using main will produce an error during apt-get update)

For now the installation starts fine!

**Comment by fg2it** [comment]
@Atrejoe Thanks for the missing `deb`. I updated the wiki accordingly.

> Wow I overlooked the remark:

Yes, you did 😉. But I have to admit I could have put more emphasis on that point.
