### ISSUE TITLE
Make executable available

### ISSUE THREAD

**Issue by wilsonmar** [fg2it/grafana-on-raspberry#9]
Is it possible you put the results in an Executables folder so it can be used without me setting up the re-compile myself? Yes, I'm that lazy.

**Comment by vimagick** [comment]
It can be extracted from deb package.

**Comment by fg2it** [comment]
@wilsonmar I am not sure to understand correctly what you are wanting. Strictly speaking, the first part of your sentence would mean for me to provide `grafana-server` and `grafana-cli`, the "executables". But, the last part of your sentence ("re-compile") shed some doubt on this interpretation.

Currently, I provide `.deb` and `tar.gz` in the [release](https://github.com/fg2it/grafana-on-raspberry/releases) section for rpi 2/3 and .deb on debian repo, hosted on bintray, for rpi1 and rpi 2/3 (see the [wiki](https://github.com/fg2it/grafana-on-raspberry/wiki) for details).

So, If you want "executables", you don't have to re-compile yourself. It is a simple matter of downloading and extracting. This is quite obvious with `.tar.gz`, eg :
```bash
$ curl -LO https://github.com/fg2it/grafana-on-raspberry/releases/download/v4.0.0-beta2-testing/grafana-4.0.0-1479761438beta2.linux-armhf.tar.gz
$ tar xvfz grafana-4.0.0-1479761438beta2.linux-armhf.tar.gz
#grafana-cli and grafana-server are in ./grafana-4.0.0-1479761438beta2/bin
```
(you can even avoid to extract the full `.tar.gz` with some less used `tar` option).

But it is also quite easy to extract from `.deb` as said by @vimagick :
```bash
$ curl -LO https://github.com/fg2it/grafana-on-raspberry/releases/download/v4.0.0-beta2-testing/grafana_4.0.0-1479761438beta2_armhf.deb
$ dpkg -x grafana_4.0.0-1479761438beta2_armhf.deb ./grafana_4.0.0-beta2
#grafana-cli and grafana-server are in grafana_4.0.0-beta2/usr/sbin/
```
(if you are looking for pi1, see the [bintray](https://dl.bintray.com/fg2it/deb-rpi-1b/testing/g/) repo for download link)

Finally, what is your use case ? grafana needs some files other than the 2 executables.
